services:
  app:
    image: quay.io/toska/gptwrapper:ci
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=3000
      - AZURE_API_KEY=asdasd
      - AZURE_RESOURCE=asdasd
      - CI=true
      - PUBLIC_URL=http://localhost:8000
    ports:
      - 8000:3000
    container_name: gptwrapper

  db:
    image: docker.io/postgres:15.2-alpine
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
    container_name: gptwrapper_db

  redis:
    image: redis:7-alpine
    container_name: gptwrapper_redis

volumes:
  pg_data: