import InfoText from '../models/infotext'

const infoTexts = [
  {
    name: 'disclaimer',
    text: {
      fi: 'CurreChat on Helsingin yliopistossa kehitetty generatiivisen tekoälyn työkalu. Palvelusta vastaa HY:n opetusteknlogiapalvelut (OTE). CurreChat on kehitetty erityisesti opetuksen tarpeisiin. Yleisempään käyttöön suositeltu generatiivisen tekoälyn palvelu yliopistolla on [Microsoft 365 Copilot](hhttps://helpdesk.it.helsinki.fi/help/20071).\n\n**Huom!** CurreChat on aktiivisesti kehitettävä palvelu ja sen toiminnallisuuksiin ja käyttöliittymään voi ajoittain tulla pieniä muutoksia. Hetkelliset käyttökatkot tai toimintahäiriöt ovat mahdollisia. \n\n### Pääsy palveluun ja käyttö kursseilla\n\nCurreChat on vapaasti käytettävissä Helsingin yliopiston henkilökunnalle. Yliopiston opiskelijat pääsevät käyttämään CurreChatia opettajan aktivoimilla kursseilla kurssin keston ajan.\n\n### Käyttörajat\n\nKehittyneempien kielimallien käyttö on rajattu tiettyyn määrään tokeneita. Henkilökohtaisessa käytössä laskuri nollautuu kuukausittain. Kursseilla opiskelijoilla on käytössään tietty määrä tokeneita koko kurssin ajalle.\n\nTokenien kulutusta voi vähentää tyhjentämällä keskustelu aina keskustelun aiheen vaihtuessa. Kevyempien mini-päätteisten kielimallien käyttö ei kuluta token-laskuria.\n\n### Tietoturva ja käyttäjän vastuu\n\nCurreChat noudattaa EU:n yleistä tietosuoja-asetusta (GDPR). Käydyt keskustelut ovat yksityisiä eivätkä tallennu järjestelmään. Käyttäjällä on mahdollisuus tallentaa keskustelu lähettämällä se itselleen sähköpostina. Palveluun syötettyjä aineistoja ei käytetä kielimallien opetukseen.\n\nCurreChatissa ei saa käsitellä luottamuksellisia tai salaisia tietoja ja käyttäjän tulee varmistaa, että hänellä on riittävät oikeudet syöttämiensä materiaalien käsittelyyn palvelussa.\n\n**Ohjeita ja lisätietoa**\n\n- [Tekoäly opetuksessa](https://teaching.helsinki.fi/ohjeet/node/3923) (Opetustyön ohjeet)\n- [Tekoälyn käyttö oppimisen tukena](https://studies.helsinki.fi/ohjeet/node/3968) (Opiskelu-palvelu)\n- [Generatiivinen teköäly yliopistolla](https://helpdesk.it.helsinki.fi/help/20064) (IT-HelpDesk)\n- [Generatiivisen tekoälyn käytön yleiset periaatteet](https://flamma.helsinki.fi/s/AHCgm) (Flamma)\n- CurreChatiin liittyvissä kysymyksissä voit olla yhteydessä osoitteeseen [opetusteknologia@helsinki.fi](mailto:opetusteknologia@helsinki.fi)',

      sv: '### Instruktioner för användning av CurreChat\n\nVarje användare har tillgång till 150 000 tokens för språkmodellen GPT-4o. Detta saldo återställs varje månad. **För att minska förbrukningen av tokens bör du rensa konversationen** med knappen RADERA KONVERSATION varje gång du byter ämne för konversationen. Användning av språkmodellen GPT-4o-mini förbrukar inte tokens. Du kan se förbrukningen av tokens och den språkmodell som används längst ner i konversationsfönstret.\n\n**När du rensar konversationen raderas den gamla konversationen.**\n\nDu kan spara din konversation via e-post genom att trycka på knappen SPARA SOM E-POST.\n\nNär du använder AI-verktyg, undvik att dela data som du inte är säker på att du har rätt att dela. När du matar in data i ett AI-verktyg ska du se till att du tar hänsyn till eventuella sekretessbegränsningar och att du har fått nödvändiga upphovsrättstillstånd etc. för att dela de data som tillhandahålls. Användning av obehöriga data i AI-system kan leda till intrång i tredje parts immateriella rättigheter.\n\n### Om CurreChat\n\nCurreChat använder stora språkmodeller som utvecklats av OpenAI och som finns på Microsoft Azure-molntjänsten vid Helsingfors universitet i EU.  De uppgifter som matas in i tjänsten kommer inte att användas för ytterligare utbildning av språkmodellen.  Dessutom överförs inga användaridentifieringsdata till språkmodellen.\n\nDu kan läsa mer om de tokens som används av de viktigaste språkmodellerna här: [https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them)\n\nMer information om användningen av AI inom utbildning finns på: [https://teaching.helsinki.fi/instruktioner/artikel/artificiell-intelligens-i-undervisningen](https://teaching.helsinki.fi/instruktioner/artikel/artificiell-intelligens-i-undervisningen)\n\nVid frågor som rör CurreChat-tjänsten kan du kontakta: [opetusteknologia@helsinki.fi](mailto:opetusteknologia@helsinki.fi)',

      en: `CurreChat is a generative AI tool developed at the University of Helsinki. The service is maintained by the University’s Educational Technology Services (OTE). CurreChat has been designed specifically for the needs of teaching. For more general use, the university recommends [Microsoft 365 Copilot](https://helpdesk.it.helsinki.fi/en/help/20071).\n\n**Note!** CurreChat is an actively developed service, and its functionalities and user interface may occasionally undergo small changes. Temporary outages or malfunctions are possible.\n\n### Access to the service and use in courses\n\nCurreChat is freely available to the staff of the University of Helsinki. University students can use CurreChat in courses where the teacher has enabled it for the duration of the course.\n\n### Usage limits\n\nThe use of more advanced language models is limited by a set number of tokens. For personal use, the counter resets monthly. In courses, students are provided with a certain number of tokens for the entire course.\n\nToken consumption can be reduced by clearing the conversation whenever the topic changes. The use of lighter, mini-suffixed language models does not deplenish the user's token quota.\n\n### Data security and user responsibility\n\nCurreChat complies with the EU General Data Protection Regulation(GDPR).Conversations are private and are not stored in the system.Users can choose to save a conversation by sending it to themselves via email.Materials entered into the service are not used to train language models.\n\nConfidential or secret information must not be processed in CurreChat, and the user must ensure that they have sufficient rights to handle the materials they input into the service.\n\n**Instructions and further information**\n\n * [Artificial intelligence in teaching](https://teaching.helsinki.fi/instructions/article/artificial-intelligence-teaching) (Instructions for teachers)\n* [Using AI to Support Learning](https://studies.helsinki.fi/instructions/article/using-ai-support-learning) (Studies service)\n* [Generative AI at the University](https://helpdesk.it.helsinki.fi/en/help/20064) (IT HelpDesk)\n* [Policy for the use and development of artificial intelligence](https://flamma.helsinki.fi/s/4GSqe) (Flamma)\n* For questions about CurreChat, please contact [edutech@helsinki.fi](mailto:edutech@helsinki.fi)`,
    },
  },
  {
    name: 'systemMessage',
    text: {
      fi: 'Alusta keskustelu antamalla yleistason ohjeita tekoälylle',
      sv: 'Initialize the conversation by giving high level instructions to the AI',
      en: 'Initialize the conversation by giving high level instructions to the AI',
    },
  },
  {
    name: 'mathGuide',
    text: {
      fi: '## Matematiikan muotoiluohje\nMatemaattiset kaavat tulee ympäröidä kahdella dollarimerkillä `$$` (rivinsisäinen muotoilu yhdellä dollarimerkillä `$` ei ole tuettu). Tasattujen yhtälöiden osalta käytä `aligned`-ympäristöä `$$...$$`-lohkon sisällä; tasaus merkitään `&`-merkillä ja rivinvaihto `\\\\`-merkillä. Matriisit: käytä `pmatrix`, `bmatrix`, `vmatrix`, `Vmatrix` tai `matrix`-ympäristöä `$$...$$`-lohkon sisällä. Kemialliset kaavat: `\\ce{...}`; yksiköt: `\\pu{...}`. Tuetut makrot: `\\abs{x}` |x|, `\\norm{v}` ||v||, `\\R` ℝ, `\\C` ℂ, `\\N` ℕ, `\\Z` ℤ, `\\vec{a}` **a**, `\\deriv{y}{x}` dy/dx, `\\pdv{f}{x}` ∂f/∂x, `\\set{S}` {S}, `\\lr{expr}` (expr), `M\\T` M^T, `A \\defeq B` A := B, `\\epsilon_0` ε₀, `\\mu_0` μ₀, `\\div` div, `\\curl` curl, `\\grad` grad, `\\laplacian` ∇², `\\dd{x}` dx, `\\pd{x}` ∂x, `\\vb{A}` **A**, `\\vu{e}` ê, `\\aprx` ≈, `\\bra{A}` ⟨A|, `\\ket{B}` |B⟩, `\\braket{A}{B}` ⟨A|B⟩, `\\oprod{A}{B}` |A⟩⟨B|, `\\slashed{A}` Ā.',
      en: '## Math formatting guide\nWrap math with double dollar signs `$$` (inline math with `$` is not supported). For aligned equations, use `aligned` inside `$$...$$` with `&` for alignment and `\\\\` for new lines. Matrices: use `pmatrix`, `bmatrix`, `vmatrix`, `Vmatrix`, or `matrix` inside `$$...$$`. Chemical formulas: `\\ce{...}`; units: `\\pu{...}`. Supported macros: `\\abs{x}` |x|, `\\norm{v}` ||v||, `\\R` ℝ, `\\C` ℂ, `\\N` ℕ, `\\Z` ℤ, `\\vec{a}` **a**, `\\deriv{y}{x}` dy/dx, `\\pdv{f}{x}` ∂f/∂x, `\\set{S}` {S}, `\\lr{expr}` (expr), `M\\T` M^T, `A \\defeq B` A := B, `\\epsilon_0` ε₀, `\\mu_0` μ₀, `\\div` div, `\\curl` curl, `\\grad` grad, `\\laplacian` ∇², `\\dd{x}` dx, `\\pd{x}` ∂x, `\\vb{A}` **A**, `\\vu{e}` ê, `\\aprx` ≈, `\\bra{A}` ⟨A|, `\\ket{B}` |B⟩, `\\braket{A}{B}` ⟨A|B⟩, `\\oprod{A}{B}` |A⟩⟨B|, `\\slashed{A}` Ā.',
      sv: '## Guide för matematisk formatering\nMatematiska uttryck ska omges av dubbla dollartecken `$$` (inline-formatering med `$` stöds inte). För justerade ekvationer, använd `aligned` inuti `$$...$$` med `&` för justering och `\\\\` för nya rader. Matriser: använd `pmatrix`, `bmatrix`, `vmatrix`, `Vmatrix` eller `matrix` inuti `$$...$$`. Kemiska formler: `\\ce{...}`; enheter: `\\pu{...}`. Makron som stöds: `\\abs{x}` |x|, `\\norm{v}` ||v||, `\\R` ℝ, `\\C` ℂ, `\\N` ℕ, `\\Z` ℤ, `\\vec{a}` **a**, `\\deriv{y}{x}` dy/dx, `\\pdv{f}{x}` ∂f/∂x, `\\set{S}` {S}, `\\lr{expr}` (expr), `M\\T` M^T, `A \\defeq B` A := B, `\\epsilon_0` ε₀, `\\mu_0` μ₀, `\\div` div, `\\curl` curl, `\\grad` grad, `\\laplacian` ∇², `\\dd{x}` dx, `\\pd{x}` ∂x, `\\vb{A}` **A**, `\\vu{e}` ê, `\\aprx` ≈, `\\bra{A}` ⟨A|, `\\ket{B}` |B⟩, `\\braket{A}{B}` ⟨A|B⟩, `\\oprod{A}{B}` |A⟩⟨B|, `\\slashed{A}` Ā.',
    },
  },
]

const seedInfoTexts = async () => {
  const operations: any[] = []
  infoTexts.forEach((infoText) => {
    const operation = InfoText.upsert({
      ...infoText,
    })

    operations.push(operation)
  })

  await Promise.all(operations)
}

export default seedInfoTexts
