name: Build and push docker image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'dalai/**'
      - '.github/workflows/dalai.yaml'

jobs:
  build-and-push:
    if: ${{ github.actor != 'renovate[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.version.helsinki.fi/toska/openshift/kontit/
          username: kontit
          password: ${{ secrets.VERSION_PUSH_SECRET }}
          
      - name: Build and push the Docker image
        env:
          IMAGE: registry.version.helsinki.fi/toska/openshift/kontit/dalai
          SHA: ${{ github.sha }}
        run: |-
          docker build -t $IMAGE:build ./dalai

          docker tag $IMAGE:build $IMAGE:latest
          docker tag $IMAGE:build $IMAGE:$SHA

          docker push $IMAGE:latest
          docker push $IMAGE:$SHA
